### ISSUE TITLE
Release 0.1

### ISSUE THREAD

**Issue by kojisekig** [LTR4L/ltr4l#195]
After Lucene (#165) and Solr (#166) are implemented, let's release 0.1.0!

**Comment by kojisekig** [comment]
I'd like to have CHANGES.txt that tells the change history of this project, from the beginning.

**Comment by yasufumi0410** [comment]
I finished releasing v0.1.0.
See https://github.com/LTR4L/ltr4l/releases/tag/rel-0.1.0
