### ISSUE TITLE
Incorrect report

### ISSUE THREAD

**Issue by Pryanic** [LTR4L/ltr4l#303]
Hi guys.
Your tool is wonderful!
But I faced with problem, I don't understand the report, could you help me understanding of WEIGHTS, and why the  report contains three section of weights I expect just two for input weights of first lvl and for input weights of second lvl
```
{
  "config" : {
    "algorithm" : "RankNet",
    "numIterations" : 20,
    "batchSize" : 10,
    "verbose" : true,
    "nomodel" : false,
    "params" : {
      "learningRate" : 1.0E-5,
      "optimizer" : "adam",
      "weightInit" : "xavier",
      "regularization" : {
        "regularizer" : "L2",
        "rate" : 0.01
      },
      "layers" : [ {
        "activator" : "Sigmoid",
        "num" : 2
      }, {
        "activator" : "Sigmoid",
        "num" : 1
      } ]
    },
    "dataSet" : {
      "training" : "/ltr4l/Data/train.txt",
      "validation" : "/ltr4l/Data/vali.txt",
      "test" : "/ltr4l/Data/test.txt"
    },
    "model" : {
      "format" : "json",
      "file" : "model/ranknet-model.json"
    },
    "evaluation" : {
      "evaluator" : "ndcg",
      "params" : {
        "k" : 10
      }
    },
    "report" : {
      "format" : "csv",
      "file" : "report/ranknet-report.csv"
    }
  },
  "weights" : [ 
     [ [ 0.006921108944583758, 0.003099679775395407, 0.011995035180251357 ] ], [ [ 0.009999403017790252, -0.017508053122632775 ] ] ]
}
```
Please help me with it

**Comment by Kamulau** [comment]
Thanks for your comment! I would like a little bit more information about how you obtained this particular model (i.e. how did you conduct the training etc...), however I can provide this insight regarding the weights:

The first index is layer number, the second index is node number, and the third index is the edge/weight number. The current implementation of neural network based ltr algorithms have a set output layer, and so all layers specified are hidden layers. So what this looks like to me is the last two weights

```
[ 0.009999403017790252, -0.017508053122632775 ]
```
are the bias and the weight between the last hidden layer with one sigmoid and the output identity layer (which is constructed automatically for the Rank Net architecture).
The three weights before that:
```
[ 0.006921108944583758, 0.003099679775395407, 0.011995035180251357 ]
```
should correspond to the bias and the weights between each of the nodes in the 2/sigmoid layer and 1/sigmoid layer. There should actually be one more set of weights, corresponding to the edges between the input layer and the first hidden layer, but that seems to be missing; how big was your input layer, and how did you construct the network?

**Comment by Pryanic** [comment]
Thank you for answer, I don't think that output edge has a weight, now I clear see it. Thank you a lot for you wonderful tool. I didn't put the weights for first layer because it was too large.
