### ISSUE TITLE
ant test -Dtestcase doesn't work

### ISSUE THREAD

**Issue by kojisekig** [LTR4L/ltr4l#87]
After Jacoco is introduced, it doesn't work.

**Comment by yasufumi0410** [comment]
I think we should rename the task for calculate coverage such as **coverage** or **coverage-report**, and simplify **test** task.

**Comment by kojisekig** [comment]
I think it's fine.

**Comment by kojisekig** [comment]
I think ant test -Dtestcase still doesn't work

**Comment by kojisekig** [comment]
This feature has never been implemented from the beginning! Jacoco stuff didn't break anything!
